var projects = [{
	"title" : "Homes to Domes",
	"users" : "Museum Goers and Community Members",
	"role" : "User Experience, Developer, Designer",
	"slides" : ["thesis/domes01", "thesis/domes02", "thesis/001", "thesis/002", "thesis/003", "thesis/004", "thesis/005", "thesis/006", "thesis/007", "thesis/008", "thesis/009", "thesis/010", "thesis/014", "thesis/013", "thesis/015"],
	'id' : 3,
},{
	"title" : "Public Involvement",
	"users" : "Vine City & English Avenue Residents",
	"role" : "User Experience, Development",
	"slides" : ["public/public01", "public/public02", "public/pd04", "public/pd05", "public/pd03", "public/pd02", "public/pd01"],
	'id' : 5,
},
{
	"title" : "Porsche Digitalization",
	"users" : "Building Visitors, Porsche Enthusiasts",
	"role" : "Front End Developer",
	"slides" : ["porsche/porsche01", "porsche/porsche02", "porsche/p04", "porsche/p05", "porsche/p01", "porsche/p02", "porsche/p03"],
	'id' : 7,
},
{
	"title" : "Trees Atlanta Table",
	"users" : "Children, Families",
	"role" : "User Experience, Developer",
	"slides" : ["table/trees01", "table/trees02", "table/t02", "table/t05", "table/t03", "table/t04", "table/t01","table/t06", "table/t07"],
	'id' : 2,
},
{
	"title" : "Explorers the Game",
	"users" : "Children, Teachers",
	"role" : "User Experience, Developer",
	"slides" : ["explorers/explorers01", "explorers/explorers02", "explorers/e04", "explorers/e05", "explorers/e06", "explorers/e07", "explorers/e08"],
	'id' : 4,
},
{
	"title" : "Mapping iThemba",
	"users" : "Researchers, Scholars",
	"role" : "Visual Designer, Developer",
	"slides" : ["ithemba/ithemba01", "ithemba/ithemba02", "ithemba/i03", "ithemba/i01", "ithemba/i02"],
	'id' : 6,
},]